-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUvm+PX9ODqGaeTsM
fWasXb2yIeeWyc9Q0Ndari0qJkugCgYIKoZIzj0DAQehRANCAASgkIZBqHyvfX3B
Dmups+ZNypyW2DpPLlDYnROF2A3GDc6htm/4KWxnytHD0LJuWEb6ANLBRfYFQlso
ZLSQrXo0
-----END PRIVATE KEY-----